flash_cards_django/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('deck/', views.deck_create, name='deck-create'),
    path('deck/<int:id>/', views.deck_edit, name='deck-edit'),
    path('card/', views.card_create, name='card-create'),
    path('card/<int:id>/', views.card_edit, name='card-edit'),
]

flash_cards_django/flash_cards_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

flash_cards_django/core/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Tag(BaseModel):
    """Easy categorize your flashcards grouping them by tag"""
    name = models.CharField(max_length=50, unique=True, blank=False, null=False)


class Deck(BaseModel):
    """Let's you organize your flashcards in groups for partial repetition"""
    title = models.CharField(max_length=100, blank=False, null=False)
    description = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return self.title


class FlashCard(BaseModel):
    front = models.TextField(blank=False)
    back = models.TextField(blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    decks = models.ManyToManyField(Deck)
    is_question = models.BooleanField(default=False)


class Hint(BaseModel):
    """Extra info for helping on repetition session"""
    content = models.TextField(blank=False)
    flash_card = models.ForeignKey(FlashCard, on_delete=models.CASCADE)


class PossibleChoice(BaseModel):
    content = models.TextField()
    flash_card = models.ForeignKey(FlashCard, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)


# class RepetitionDeck(BaseModel):
#     repetition_session = models.ForeignKey(
#         RepetitionSession, on_delete=models.CASCADE)
#     deck = models.ForeignKey(Deck, on_delete=models.CASCADE)


class TextAnswer(BaseModel):
    content = models.TextField()
    flash_card = models.ForeignKey(FlashCard, on_delete=models.CASCADE)


class DeckReviewedEvent(BaseModel):
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)


class FlashCardReviewedEvent(BaseModel):
    flash_card = models.ForeignKey(FlashCard, on_delete=models.CASCADE)

flash_cards_django/core/forms.py
from django import forms
from .models import Deck, FlashCard, Tag


class DeckForm(forms.ModelForm):
    title = forms.CharField(label="Title", max_length=100, required=True)
    description = forms.CharField(label="Description", max_length=250, required=False)

    class Meta:
        model = Deck
        fields = "__all__"


class FlashCardForm(forms.ModelForm):
    front = forms.Textarea()
    back = forms.Textarea()
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False)
    decks = forms.ModelMultipleChoiceField(queryset=Deck.objects.all())
    is_question = forms.CheckboxInput()

    class Meta:
        model = FlashCard
        fields = "__all__"

flash_cards_django/core/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpRequest

from .forms import DeckForm, FlashCardForm
from .models import Deck, FlashCard


def index(request: HttpRequest):
    decks = Deck.objects.all()
    return render(request, 'core/index.html', {"decks": decks})


def deck_create(request: HttpRequest,):
    if request.method == "POST":
        deck_form = DeckForm(request.POST)
        if deck_form.is_valid():
            new_deck_data = deck_form.save()
            return redirect(reverse("core:deck-edit", args=[new_deck_data.id]))
    # if GET request or invalid form
    deck_form = DeckForm()
    return render(request, 'core/deck/create.html', {"deck_form": deck_form})


def deck_edit(request: HttpRequest, id: int):
    if request.method == "POST":
        deck_form = DeckForm(request.POST)
        if deck_form.is_valid():
            deck_form.save()
            return redirect(reverse('core:index'))
    deck = get_object_or_404(Deck, pk=id)
    deck_form = DeckForm(instance=deck)
    flash_cards = FlashCard.objects.filter(decks__pk=id)
    context = {
        "deck_form": deck_form,
        "deck": deck,
        "flash_cards": flash_cards}

    return render(request, 'core/deck/edit.html', context)


def card_create(request: HttpRequest):
    deck_id = request.GET.get("deck", None)
    if request.method == "POST":
        card_form = FlashCardForm(request.POST)
        if card_form.is_valid():
            card_form.save()
            if deck_id is not None:
                try:
                    deck = Deck.objects.get(pk=deck_id)
                    redirect(reverse('core:deck-edit', args=[deck.id]))
                except ObjectDoesNotExist:
                    return redirect(reverse('core:index'))
            return redirect(reverse('core:index'))

    card_form = FlashCardForm()
    return render(request, "core/flash_card/create.html",
                  {"card_form": card_form})


def card_edit(request: HttpRequest, id: int):
    if request.method == "POST":
        card_form = FlashCardForm(request.POST, instance=FlashCard.objects.get(pk=id))
        if card_form.is_valid():
            print("saving card")
            card_form.save()
            return redirect(reverse('core:card-edit', args=[id]))

    print("loading card")
    card = get_object_or_404(FlashCard, pk=id)
    card_form = FlashCardForm(instance=card)
    return render(request, 'core/flash_card/edit.html', {"card_form": card_form})

flash_cards_django/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Flash cards{% endblock %}</title>
</head>
<body>
   {% block content %} {% endblock %}
</body>
</html>

flash_cards_django/core/templates/core/deck/create.html
{% extends 'core/base.html' %}

{% block title %} Create new Deck {% endblock %}

{% block content %}
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        {{ deck_form.as_div}}
        <button type="submit">Create Deck</button>
    </form>
{% endblock %}

flash_cards_django/core/templates/core/deck/edit.html
{% extends 'core/base.html' %}

{% block title %} Modify Deck {% endblock %}

{% block content %}
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        {{ deck_form.as_div}}
        <button type="submit">Modify Deck</button>
    </form>
    <div>
        <div>
            <a href="{% url 'core:card-create'%}?deck={{deck.id}}">New card</a>
        </div>
        {% for card in flash_cards %}
            <div>
                <ul>
                {% for tag in card.tags_set.all %}
                    <li> #{{ tag.name }}</li>
                {% endfor %}
                </ul>
                <a href="{% url 'core:card-edit' card.id %}">Edit</a>
                <p>{{ card.front }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

flash_cards_django/core/templates/core/flash_card/create.html
{% extends 'core/base.html' %}

{% block title %} Create new Card {% endblock %}

{% block content %}
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        {{ card_form.as_div}}
        <button type="submit">Create Card</button>
    </form>
{% endblock %}

flash_cards_django/core/templates/core/flash_card/edit.html
{% extends 'core/base.html' %}

{% block title %} Modify Card {% endblock %}

{% block content %}
    <form action="{{request.path}}" method="POST">
        {% csrf_token %}
        {{ card_form.as_div}}
        <button type="submit">Modify Card</button>
    </form>
{% endblock %}

flash_cards_django/core/templates/core/index.html
{% extends 'core/base.html'%}
{% block title %} Flash cards - Main page {% endblock %}

{% block content %}
    <h1>Created DECKS</h1>
    <div>
        <a href="{% url 'core:deck-create' %}"> Create deck</a>
    </div>
    {% for deck in decks %}
    <div>
        <a href="{% url 'core:deck-edit' deck.id %}">{{ deck.title }}</a>
    </div>
    {% endfor %}
{% endblock %}